// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeBaNV4cgbiMGxubSmeBfRocJij_Bn_3w',
    appId: '1:764524226349:web:4cf4917dc4fed5ade115a4',
    messagingSenderId: '764524226349',
    projectId: 'mygoals-19463',
    authDomain: 'mygoals-19463.firebaseapp.com',
    storageBucket: 'mygoals-19463.firebasestorage.app',
    measurementId: 'G-MBC832E2GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPMsjAlUqkSbXOnDkpdv9vSVz47D5GSM',
    appId: '1:764524226349:android:3207b27ea52d3a83e115a4',
    messagingSenderId: '764524226349',
    projectId: 'mygoals-19463',
    storageBucket: 'mygoals-19463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRyLlrC6JQ8iMOuJCNWfj6DHCaxRamKmM',
    appId: '1:764524226349:ios:5fe0d53eeb4bacd6e115a4',
    messagingSenderId: '764524226349',
    projectId: 'mygoals-19463',
    storageBucket: 'mygoals-19463.firebasestorage.app',
    iosClientId: '764524226349-0dhuper1bvfmh3lush7mff4qdkmjes4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
